-- ユーザープロファイルテーブル
CREATE TABLE user_profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  gender TEXT,
  height_cm DECIMAL,
  target_weight_kg DECIMAL,
  daily_calorie_goal INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 食事ログテーブル
CREATE TABLE meal_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  food_name TEXT,
  calories DECIMAL,
  protein DECIMAL,
  fat DECIMAL,
  carbs DECIMAL,
  logged_at DATE DEFAULT CURRENT_DATE
);

-- AI Analysis Cache Table
CREATE TABLE IF NOT EXISTS ai_analysis_cache (
    image_hash TEXT PRIMARY KEY,
    result_json TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
